# Generated by Django 3.0.5 on 2020-04-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0002_room_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
    ]
