# Generated by Django 3.0.5 on 2020-04-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0003_remove_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('king smoking', 'KS'), ('king nonsmoking', 'KNS'), ('king nonsmoking handicap', 'KNSH'), ('king smoking handicap', 'KSH')], default='KS', max_length=140),
        ),
    ]
