# Generated by Django 3.0.5 on 2020-04-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0005_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomfloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_floor', models.CharField(choices=[('1st floor', '1st floor'), ('2nd floor', '2nd floor'), ('3rd floor', '3rd floor')], default='1st floor', max_length=50)),
            ],
        ),
    ]
