# Generated by Django 3.0.5 on 2020-04-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0007_auto_20200424_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='rroom_floor',
            new_name='room_floor',
        ),
    ]
