# Generated by Django 3.0.5 on 2020-04-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0008_auto_20200424_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(default='', max_length=140),
        ),
    ]
