# Generated by Django 3.0.5 on 2020-04-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0009_auto_20200424_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number']},
        ),
    ]
