# Generated by Django 3.0.5 on 2020-06-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0013_auto_20200611_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('king smoking', 'KS'), ('king nonsmoking', 'KNS'), ('king nonsmoking handicap', 'KNSH'), ('king smoking handicap', 'KSH'), ('queen smoking', 'QS'), ('queen nonsmoking', 'QNS'), ('queen nonsmoking handicap', 'QNSH'), ('queen smoking handicap', 'QSH')], default='KS', max_length=140),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(choices=[('king smoking', 'KS'), ('king nonsmoking', 'KNS'), ('king nonsmoking handicap', 'KNSH'), ('king smoking handicap', 'KSH'), ('queen smoking', 'QS'), ('queen nonsmoking', 'QNS'), ('queen nonsmoking handicap', 'QNSH'), ('queen smoking handicap', 'QSH')], default='KS', max_length=140),
        ),
    ]
