# Generated by Django 3.0.5 on 2020-06-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0014_auto_20200617_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_status', models.CharField(choices=[('1st floor', '1st floor'), ('2nd floor', '2nd floor'), ('3rd floor', '3rd floor')], default='maintenance', max_length=50)),
            ],
        ),
    ]
