# Generated by Django 3.0.5 on 2020-06-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0015_roomstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstatus',
            name='room_status',
            field=models.CharField(choices=[('clean', 'clean'), ('dirty', 'dirty'), ('maintenance', 'maintenance')], default='maintenance', max_length=50),
        ),
    ]
