# Generated by Django 3.0.5 on 2020-08-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0017_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='comment2',
            field=models.CharField(default='', max_length=140),
        ),
    ]
