# Generated by Django 3.0.5 on 2020-08-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0018_test_comment2'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomClean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Roomnumber', models.CharField(default='', max_length=140)),
                ('Clean_Under_Bedding', models.BooleanField()),
                ('Insects_Check', models.BooleanField()),
                ('replace_Bedspread', models.BooleanField()),
                ('replace_Pillow_Covers', models.BooleanField()),
                ('Clean_Replace_Blankets', models.BooleanField()),
                ('Clean_Night_Stand', models.BooleanField()),
                ('Clean_Windows', models.BooleanField()),
                ('Clean_Curtain', models.BooleanField()),
                ('Clean_Mirrors', models.BooleanField()),
                ('Hanger_Regular', models.CharField(default='', max_length=140)),
                ('Hanger_clipper', models.CharField(default='', max_length=140)),
                ('Clean_Tv_Furniture', models.BooleanField()),
                ('Clean_Tv_Under_Furniture', models.BooleanField()),
                ('Clean_Tv_Furniture_drawers', models.BooleanField()),
                ('Clean_Desk_Furniture', models.BooleanField()),
                ('Clean_Desk_Chair', models.BooleanField()),
                ('Clean_Phone', models.BooleanField()),
                ('Check_Phone', models.BooleanField()),
                ('Clean_Tv', models.BooleanField()),
                ('Check_Tv', models.BooleanField()),
                ('Check_Remote', models.BooleanField()),
                ('Clean_Microwave', models.BooleanField()),
                ('Clean_Fridge', models.BooleanField()),
                ('Check_Microwave', models.BooleanField()),
                ('Check_Fridge', models.BooleanField()),
                ('Clean_AC', models.BooleanField()),
                ('Check_AC', models.BooleanField()),
                ('Clean_Floor', models.BooleanField()),
                ('Ice_Bucket', models.BooleanField()),
                ('Water_Cups', models.BooleanField()),
                ('Marketing_Material', models.BooleanField()),
                ('Clean_Toilet', models.BooleanField()),
                ('Clean_Shower_Curtain', models.BooleanField()),
                ('Clean_Shower_Head', models.BooleanField()),
                ('Clean_Bathtub', models.BooleanField()),
                ('Clean_Sink', models.BooleanField()),
                ('Clean_Venity', models.BooleanField()),
                ('Clean_Venity_Mirror', models.BooleanField()),
                ('Toilet_Paper', models.BooleanField()),
                ('Bath_Towel', models.CharField(default='', max_length=6)),
                ('Hand_Towel', models.CharField(default='', max_length=6)),
                ('Wash_Cloth', models.CharField(default='', max_length=6)),
                ('Bath_Mate', models.CharField(default='', max_length=140)),
                ('Bath_Soap', models.CharField(default='', max_length=140)),
                ('Clean_Bathroom_Floor', models.BooleanField()),
                ('Check_Smoke_Alarm', models.BooleanField()),
                ('Check_Latch', models.BooleanField()),
                ('Check_Lock', models.BooleanField()),
                ('Check_Door_Stickers', models.BooleanField()),
                ('Comment', models.CharField(max_length=140)),
            ],
        ),
    ]
