# Generated by Django 3.0.5 on 2020-07-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0021_remove_deepclean_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepclean',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
