# Generated by Django 3.0.5 on 2020-07-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0023_deepclean_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepclean',
            name='time',
            field=models.TimeField(),
        ),
    ]
