# Generated by Django 3.0.5 on 2020-07-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0025_remove_deepclean_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepclean',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
