# Generated by Django 3.0.5 on 2020-07-31 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0030_deepclean_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepclean',
            name='date',
        ),
    ]
