# Generated by Django 3.0.5 on 2020-07-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0033_auto_20200731_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepclean',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
