# Generated by Django 3.0.5 on 2020-08-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0035_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roomclean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Roomnumber', models.CharField(default='', max_length=140)),
                ('Clean_Under_Bedding', models.BooleanField()),
                ('Insects_Check', models.BooleanField()),
                ('replace_Bedspread', models.BooleanField()),
                ('replace_Pillow_Covers', models.BooleanField()),
                ('Clean_Replace_Blankets', models.BooleanField()),
                ('Comment_For_Bedding', models.CharField(max_length=140)),
                ('Clean_Windows', models.BooleanField()),
                ('Clean_Mirrors', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='deepclean',
        ),
    ]
